<a href="https://colab.research.google.com/github/Areeb575/231A030_NLP-Experiments/blob/main/nlpexp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [38]:
for i, document in enumerate(document):
    print(f"Document {i + 1}: {document}")

Document 1: Machine Learning enables computers to learn from data.
Document 2: ML is a branch of Artificial Intelligence.
Document 3: Machine Learning helps computers identify patterns.
Document 4: ML algorithms can make predictions using data.
Document 5: Machine Learning is widely used in modern technology.

In [41]:
document = [
    "Machine Learning enables computers to learn from data.",
    "ML is a branch of Artificial Intelligence.",
    "Machine Learning helps computers identify patterns.",
    "ML algorithms can make predictions using data.",
    "Machine Learning is widely used in modern technology."
]

vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(document)

print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28 stored elements and shape (5, 21)>
  Coords	Values
  (0, 11)	0.32683020190778933
  (0, 10)	0.32683020190778933
  (0, 5)	0.4880162972916581
  (0, 3)	0.39372847585443144
  (0, 9)	0.4880162972916581
  (0, 4)	0.39372847585443144
  (1, 13)	0.4222421409859579
  (1, 2)	0.5233582502695435
  (1, 1)	0.5233582502695435
  (1, 8)	0.5233582502695435
  (2, 11)	0.3140366438234139
  (2, 10)	0.3140366438234139
  (2, 3)	0.3783162278555838
  (2, 6)	0.4689132131547637
  (2, 7)	0.4689132131547637
  (2, 15)	0.4689132131547637
  (3, 4)	0.3503882327118585
  (3, 13)	0.3503882327118585
  (3, 0)	0.43429718303084847
  (3, 12)	0.43429718303084847
  (3, 16)	0.43429718303084847
  (3, 19)	0.43429718303084847
  (4, 11)	0.3026366979291218
  (4, 10)	0.3026366979291218
  (4, 20)	0.4518910427672568
  (4, 18)	0.4518910427672568
  (4, 14)	0.4518910427672568
  (4, 17)	0.4518910427672568

In [42]:
print(tfidf_matrix.shape)

(5, 21)

In [43]:
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28 stored elements and shape (5, 21)>
  Coords	Values
  (0, 11)	0.32683020190778933
  (0, 10)	0.32683020190778933
  (0, 5)	0.4880162972916581
  (0, 3)	0.39372847585443144
  (0, 9)	0.4880162972916581
  (0, 4)	0.39372847585443144
  (1, 13)	0.4222421409859579
  (1, 2)	0.5233582502695435
  (1, 1)	0.5233582502695435
  (1, 8)	0.5233582502695435
  (2, 11)	0.3140366438234139
  (2, 10)	0.3140366438234139
  (2, 3)	0.3783162278555838
  (2, 6)	0.4689132131547637
  (2, 7)	0.4689132131547637
  (2, 15)	0.4689132131547637
  (3, 4)	0.3503882327118585
  (3, 13)	0.3503882327118585
  (3, 0)	0.43429718303084847
  (3, 12)	0.43429718303084847
  (3, 16)	0.43429718303084847
  (3, 19)	0.43429718303084847
  (4, 11)	0.3026366979291218
  (4, 10)	0.3026366979291218
  (4, 20)	0.4518910427672568
  (4, 18)	0.4518910427672568
  (4, 14)	0.4518910427672568
  (4, 17)	0.4518910427672568

In [44]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=["D1","D2","D3","D4", "D5"]
)

tfidf_df.round(2)

,algorithms,artificial,branch,computers,data,enables,helps,identify,intelligence,learn,...,machine,make,ml,modern,patterns,predictions,technology,used,using,widely
D1,0.00,0.00,0.00,0.39,0.39,0.49,0.00,0.00,0.00,0.49,...,0.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
D2,0.00,0.52,0.52,0.00,0.00,0.00,0.00,0.00,0.52,0.00,...,0.00,0.00,0.42,0.00,0.00,0.00,0.00,0.00,0.00,0.00
D3,0.00,0.00,0.00,0.38,0.00,0.00,0.47,0.47,0.00,0.00,...,0.31,0.00,0.00,0.00,0.47,0.00,0.00,0.00,0.00,0.00
D4,0.43,0.00,0.00,0.00,0.35,0.00,0.00,0.00,0.00,0.00,...,0.00,0.43,0.35,0.00,0.00,0.43,0.00,0.00,0.43,0.00
D5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.30,0.00,0.00,0.45,0.00,0.00,0.45,0.45,0.00,0.45

In [45]:
print(vectorizer.get_feature_names_out())

['algorithms' 'artificial' 'branch' 'computers' 'data' 'enables' 'helps'
 'identify' 'intelligence' 'learn' 'learning' 'machine' 'make' 'ml'
 'modern' 'patterns' 'predictions' 'technology' 'used' 'using' 'widely']

In [46]:
similarity_matrix = cosine_similarity(tfidf_matrix)

In [47]:
similarity_matrix

array([[1.        , 0.        , 0.35422719, 0.13795782, 0.19782163],
       [0.        , 1.        , 0.        , 0.14794868, 0.        ],
       [0.35422719, 0.        , 1.        , 0.        , 0.19007803],
       [0.13795782, 0.14794868, 0.        , 1.        , 0.        ],
       [0.19782163, 0.        , 0.19007803, 0.        , 1.        ]])

In [50]:
similarity_df = pd.DataFrame(
    similarity_matrix,
    columns=["D1", "D2", "D3", "D4", "D5"],
    index=["D1", "D2", "D3", "D4", "D5"]
)
similarity_df.round(3)

       D1     D2     D3     D4     D5
D1  1.000  0.000  0.354  0.138  0.198
D2  0.000  1.000  0.000  0.148  0.000
D3  0.354  0.000  1.000  0.000  0.190
D4  0.138  0.148  0.000  1.000  0.000
D5  0.198  0.000  0.190  0.000  1.000

In [51]:
highest_similarity = -1
most_similar_pair = None

for i in range(len(document)):
    for j in range(i + 1, len(document)):

        similarity = similarity_matrix[i][j]

        if similarity > highest_similarity:
            highest_similarity = similarity
            most_similar_pair = (i, j)

print(
    "Most similar documents: "
    f"D{most_similar_pair[0] + 1} and D{most_similar_pair[1] + 1}"
)

print(f"Similarity: {highest_similarity:.3f}")

Most similar documents: D1 and D3
Similarity: 0.354